service: syonet-algolia

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: us-east-1
  stage: production
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'
  environment:
    ALGOLIA_APPLICATION_ID: ${env:ALGOLIA_APPLICATION_ID}
    ALGOLIA_ADMIN_API_KEY: ${env:ALGOLIA_ADMIN_API_KEY}
    ALGOLIA_WWW_PAGE_INDEX: ${env:ALGOLIA_WWW_PAGE_INDEX}
    ENV: ${env:ENV}
    ALGOLIA_LAMBDA_ENDPOINT: ${env:ALGOLIA_LAMBDA_ENDPOINT}
    HTTP_WWW_HOST: ${env:HTTP_WWW_HOST}
    HTTP_OGP_HOST: ${env:HTTP_OGP_HOST}

functions:
  www_page:
    handler: src/functions/www_page/index.handler
    timeout: 900
    # events:
    #   - scheduler: cron(0 21 * * ? *) # UTC時間設定のため、-9時間
    architecture: arm64
  www_page_blogs_qiita_list:
    handler: src/functions/www_page/blogs/qiita/list.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_qiita_detail:
    handler: src/functions/www_page/blogs/qiita/detail.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_hatena_list:
    handler: src/functions/www_page/blogs/hatena/list.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_hatena_detail:
    handler: src/functions/www_page/blogs/hatena/detail.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_zenn_article_list:
    handler: src/functions/www_page/blogs/zenn/article/list.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_zenn_article_detail:
    handler: src/functions/www_page/blogs/zenn/article/detail.handler
    timeout: 900
    architecture: arm64

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    useChildProcesses: false
    allowCache: true
