service: syonet-algolia

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'development'}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'

functions:
  www_page:
    handler: src/functions/www_page/index.handler
    timeout: 900
    # events:
    #   - scheduler: cron(0 21 * * ? *) # UTC時間設定のため、-9時間
    architecture: arm64
  www_page_blogs_qiita_list:
    handler: src/functions/www_page/blogs/qiita/list.handler
    timeout: 900
    architecture: arm64
  www_page_blogs_qiita_detail:
    handler: src/functions/www_page/blogs/qiita/detail.handler
    timeout: 900
    architecture: arm64

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env.${self:provider.stage}
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    useChildProcesses: false
    allowCache: true
